Ensuring formatting fails if changed

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -29,7 +29,9 @@ jobs:
       - name: build
         run: ./scripts/ci_build.sh
       - name: formating
-        run: bazel run //tools:format
+        run: |
+          bazel run //tools:format
+          if [[ $(git status --porcelain) ]]; then echo "**** run 'bazel run //tools:format' to fix formatting errors"; exit 1; fi
       - name: test
         run: ./scripts/ci_test.sh
       - name: verify-rules-generation
